//build polygon points
function formatBuilder(a, b, c) { // return string like "200,10 250,190 160,210"
    var points = String(a.x) + "," + String(a.y) + " " + String(b.x) + "," + String(b.y) + " " +String(c.x) + "," + String(c.y);
    return points;
}
function formatRect(a, b, c, d){
	var points = String(a.x) + "," + String(a.y) + " " + String(b.x) + "," + String(b.y) + " " +String(c.x) + "," + String(c.y) + " " + String(d.x) + "," + String(d.y);
    return points;
}
//globale variable count for switch
var count = 1;
//switch for creating different polygons
switch(count){
	case 1:{
		//one circle
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "100");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	circle.onmouseout = function(){this.style.fill = "#A9F5D0";};
          	circle.onmouseover = function(){this.style.fill = "#CEF6D8";};
          	circle.style.fill = "#A9F5D0";
          	svgEle.appendChild(circle);
          	//text
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
               //minus icon
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "200");
               circle1.setAttribute("cy", "250");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line = document.createElementNS(svgNS, "line");
               line.setAttribute("x1", "194");
               line.setAttribute("y1", "250");
               line.setAttribute("x2", "206");
               line.setAttribute("y2", "250");
               line.setAttribute("stroke-width", "4");
               line.setAttribute("stroke", "white");
               line.onmouseover = function(){circle1.style.fill = "black";};
               line.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line);
               
          }
          break;
	}
	case 2:{
		//basic circle + 2 rectangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first rectangle
          	var rect1 = document.createElementNS(svgNS, "polygon");
          	rect1.setAttribute("points", formatRect({x:50, y:50}, {x:200, y:50}, {x:200, y:350}, {x:50, y:350}));
          	rect1.setAttribute("stroke-width", "1");
          	rect1.setAttribute("stroke", "black");
          	rect1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	rect1.style.fill = "#58ACFA";
          	rect1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	rect1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second rectangle
          	var rect2 = document.createElementNS(svgNS, "polygon");
          	rect2.setAttribute("points", formatRect({x:200, y:50}, {x:350, y:50}, {x:350, y:350}, {x:200, y:350}));
          	rect2.setAttribute("stroke-width", "1");
          	rect2.setAttribute("stroke", "black");
          	rect2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	rect2.style.fill = "#58ACFA";
          	rect2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	rect2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(rect1);
          	svgEle.appendChild(rect2);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "109");
          	text1.setAttribute("y", "205");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "289");
          	text2.setAttribute("y", "205");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
                //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "70");
               circle1.setAttribute("cy", "200");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "64");
               line1.setAttribute("y1", "200");
               line1.setAttribute("x2", "76");
               line1.setAttribute("y2", "200");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "330");
               circle2.setAttribute("cy", "200");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "324");
               line2.setAttribute("y1", "200");
               line2.setAttribute("x2", "336");
               line2.setAttribute("y2", "200");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
          }
          break;
	}
	case 3:{
		//circle + three triangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first triangle
          	var tri1 = document.createElementNS(svgNS, "polygon");
          	tri1.setAttribute("points", formatBuilder({x:200, y:0}, {x:200, y:200}, {x:27, y:300}));
          	tri1.setAttribute("stroke-width", "1");
          	tri1.setAttribute("stroke", "black");
          	tri1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri1.style.fill = "#58ACFA";
          	tri1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second triangle
          	var tri2 = document.createElementNS(svgNS, "polygon");
          	tri2.setAttribute("points", formatBuilder({x:200, y:0}, {x:373, y:300}, {x:200, y:200}));
          	tri2.setAttribute("stroke-width", "1");
          	tri2.setAttribute("stroke", "black");
          	tri2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri2.style.fill = "#58ACFA";
          	tri2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//third triangle
          	var tri3 = document.createElementNS(svgNS, "polygon");
          	tri3.setAttribute("points", formatBuilder({x:27, y:300}, {x:373, y:300}, {x:200, y:200}));
          	tri3.setAttribute("stroke-width", "1");
          	tri3.setAttribute("stroke", "black");
          	tri3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri3.style.fill = "#58ACFA";
          	tri3.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri3.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(tri1);
          	svgEle.appendChild(tri2);
          	svgEle.appendChild(tri3);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "128");
          	text1.setAttribute("y", "170");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "270");
          	text2.setAttribute("y", "170");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text3 = document.createElementNS(svgNS, "text");
          	text3.setAttribute("x", "198");
          	text3.setAttribute("y", "280");
          	text3.setAttribute("fill", "black");
          	text3.textContent = "3";
          	svgEle.appendChild(text3);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
                //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "160");
               circle1.setAttribute("cy", "180");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "154");
               line1.setAttribute("y1", "180");
               line1.setAttribute("x2", "166");
               line1.setAttribute("y2", "180");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "240");
               circle2.setAttribute("cy", "180");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "234");
               line2.setAttribute("y1", "180");
               line2.setAttribute("x2", "246");
               line2.setAttribute("y2", "180");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
                //minus icon 3
               var circle3 = document.createElementNS(svgNS, "circle");
               circle3.setAttribute("cx", "200");
               circle3.setAttribute("cy", "240");
               circle3.setAttribute("r", "10");
               circle3.setAttribute("stroke", "#EFFBF2");
               circle3.setAttribute("stroke-width", "1");
               circle3.setAttribute("fill", "#D8D8D8");
               circle3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle3.onmouseover = function(){this.style.fill = "black";};
               circle3.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line3 = document.createElementNS(svgNS, "line");
               line3.setAttribute("x1", "194");
               line3.setAttribute("y1", "240");
               line3.setAttribute("x2", "206");
               line3.setAttribute("y2", "240");
               line3.setAttribute("stroke-width", "4");
               line3.setAttribute("stroke", "white");
               line3.onmouseover = function(){circle3.style.fill = "black";};
               line3.onmouseout = function(){circle3.style.fill = "#D8D8D8";};
               line3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle3);
               svgEle.appendChild(line3);
          }
          break;
	}
	case 4:{
		//circle + four triangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first triangle
          	var tri1 = document.createElementNS(svgNS, "polygon");
          	tri1.setAttribute("points", formatBuilder({x:200, y:0}, {x:200, y:200}, {x:0, y:200}));
          	tri1.setAttribute("stroke-width", "1");
          	tri1.setAttribute("stroke", "black");
          	tri1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri1.style.fill = "#58ACFA";
          	tri1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second triangle
          	var tri2 = document.createElementNS(svgNS, "polygon");
          	tri2.setAttribute("points", formatBuilder({x:200, y:0}, {x:400, y:200}, {x:200, y:200}));
          	tri2.setAttribute("stroke-width", "1");
          	tri2.setAttribute("stroke", "black");
          	tri2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri2.style.fill = "#58ACFA";
          	tri2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//third triangle
          	var tri3 = document.createElementNS(svgNS, "polygon");
          	tri3.setAttribute("points", formatBuilder({x:400, y:200}, {x:200, y:400}, {x:200, y:200}));
          	tri3.setAttribute("stroke-width", "1");
          	tri3.setAttribute("stroke", "black");
          	tri3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri3.style.fill = "#58ACFA";
          	tri3.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri3.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//forth triangle
          	var tri4 = document.createElementNS(svgNS, "polygon");
          	tri4.setAttribute("points", formatBuilder({x:0, y:200}, {x:200, y:400}, {x:200, y:200}));
          	tri4.setAttribute("stroke-width", "1");
          	tri4.setAttribute("stroke", "black");
          	tri4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri4.style.fill = "#58ACFA";
          	tri4.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri4.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(tri1);
          	svgEle.appendChild(tri2);
          	svgEle.appendChild(tri3);
          	svgEle.appendChild(tri4);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "120");
          	text1.setAttribute("y", "130");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "278");
          	text2.setAttribute("y", "130");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text3 = document.createElementNS(svgNS, "text");
          	text3.setAttribute("x", "120");
          	text3.setAttribute("y", "270");
          	text3.setAttribute("fill", "black");
          	text3.textContent = "3";
          	svgEle.appendChild(text3);
          	var text4 = document.createElementNS(svgNS, "text");
          	text4.setAttribute("x", "278");
          	text4.setAttribute("y", "270");
          	text4.setAttribute("fill", "black");
          	text4.textContent = "4";
          	svgEle.appendChild(text4);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
                //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "168");
               circle1.setAttribute("cy", "168");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "162");
               line1.setAttribute("y1", "168");
               line1.setAttribute("x2", "174");
               line1.setAttribute("y2", "168");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "232");
               circle2.setAttribute("cy", "168");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "226");
               line2.setAttribute("y1", "168");
               line2.setAttribute("x2", "238");
               line2.setAttribute("y2", "168");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
                //minus icon 3
               var circle3 = document.createElementNS(svgNS, "circle");
               circle3.setAttribute("cx", "232");
               circle3.setAttribute("cy", "232");
               circle3.setAttribute("r", "10");
               circle3.setAttribute("stroke", "#EFFBF2");
               circle3.setAttribute("stroke-width", "1");
               circle3.setAttribute("fill", "#D8D8D8");
               circle3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle3.onmouseover = function(){this.style.fill = "black";};
               circle3.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line3 = document.createElementNS(svgNS, "line");
               line3.setAttribute("x1", "226");
               line3.setAttribute("y1", "232");
               line3.setAttribute("x2", "238");
               line3.setAttribute("y2", "232");
               line3.setAttribute("stroke-width", "4");
               line3.setAttribute("stroke", "white");
               line3.onmouseover = function(){circle3.style.fill = "black";};
               line3.onmouseout = function(){circle3.style.fill = "#D8D8D8";};
               line3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle3);
               svgEle.appendChild(line3);
                //minus icon 4
               var circle4 = document.createElementNS(svgNS, "circle");
               circle4.setAttribute("cx", "168");
               circle4.setAttribute("cy", "232");
               circle4.setAttribute("r", "10");
               circle4.setAttribute("stroke", "#EFFBF2");
               circle4.setAttribute("stroke-width", "1");
               circle4.setAttribute("fill", "#D8D8D8");
               circle4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle4.onmouseover = function(){this.style.fill = "black";};
               circle4.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line4 = document.createElementNS(svgNS, "line");
               line4.setAttribute("x1", "162");
               line4.setAttribute("y1", "232");
               line4.setAttribute("x2", "174");
               line4.setAttribute("y2", "232");
               line4.setAttribute("stroke-width", "4");
               line4.setAttribute("stroke", "white");
               line4.onmouseover = function(){circle4.style.fill = "black";};
               line4.onmouseout = function(){circle4.style.fill = "#D8D8D8";};
               line4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle4);
               svgEle.appendChild(line4);
          }
          break;
	}
	case 5:{
		//circle + five triangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first triangle
          	var tri1 = document.createElementNS(svgNS, "polygon");
          	tri1.setAttribute("points", formatBuilder({x:200, y:0}, {x:390, y:138}, {x:200, y:200}));
          	tri1.setAttribute("stroke-width", "1");
          	tri1.setAttribute("stroke", "black");
          	tri1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri1.style.fill = "#58ACFA";
          	tri1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second triangle
          	var tri2 = document.createElementNS(svgNS, "polygon");
          	tri2.setAttribute("points", formatBuilder({x:390, y:138}, {x:318, y:362}, {x:200, y:200}));
          	tri2.setAttribute("stroke-width", "1");
          	tri2.setAttribute("stroke", "black");
          	tri2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri2.style.fill = "#58ACFA";
          	tri2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//third triangle
          	var tri3 = document.createElementNS(svgNS, "polygon");
          	tri3.setAttribute("points", formatBuilder({x:318, y:362}, {x:82, y:362}, {x:200, y:200}));
          	tri3.setAttribute("stroke-width", "1");
          	tri3.setAttribute("stroke", "black");
          	tri3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri3.style.fill = "#58ACFA";
          	tri3.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri3.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//forth triangle
          	var tri4 = document.createElementNS(svgNS, "polygon");
          	tri4.setAttribute("points", formatBuilder({x:82, y:362}, {x:10, y:138}, {x:200, y:200}));
          	tri4.setAttribute("stroke-width", "1");
          	tri4.setAttribute("stroke", "black");
          	tri4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri4.style.fill = "#58ACFA";
          	tri4.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri4.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//fifth triangle
          	var tri5 = document.createElementNS(svgNS, "polygon");
          	tri5.setAttribute("points", formatBuilder({x:10, y:138}, {x:200, y:0}, {x:200, y:200}));
          	tri5.setAttribute("stroke-width", "1");
          	tri5.setAttribute("stroke", "black");
          	tri5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri5.style.fill = "#58ACFA";
          	tri5.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri5.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(tri1);
          	svgEle.appendChild(tri2);
          	svgEle.appendChild(tri3);
          	svgEle.appendChild(tri4);
          	svgEle.appendChild(tri5);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "130");
          	text1.setAttribute("y", "104");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "268");
          	text2.setAttribute("y", "104");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text3 = document.createElementNS(svgNS, "text");
          	text3.setAttribute("x", "312");
          	text3.setAttribute("y", "240");
          	text3.setAttribute("fill", "black");
          	text3.textContent = "3";
          	svgEle.appendChild(text3);
          	var text4 = document.createElementNS(svgNS, "text");
          	text4.setAttribute("x", "198");
          	text4.setAttribute("y", "320");
          	text4.setAttribute("fill", "black");
          	text4.textContent = "4";
          	svgEle.appendChild(text4);
          	var text5 = document.createElementNS(svgNS, "text");
          	text5.setAttribute("x", "86");
          	text5.setAttribute("y", "240");
          	text5.setAttribute("fill", "black");
          	text5.textContent = "5";
          	svgEle.appendChild(text5);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
                //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "174");
               circle1.setAttribute("cy", "164");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "168");
               line1.setAttribute("y1", "164");
               line1.setAttribute("x2", "180");
               line1.setAttribute("y2", "164");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "226");
               circle2.setAttribute("cy", "164");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "220");
               line2.setAttribute("y1", "164");
               line2.setAttribute("x2", "232");
               line2.setAttribute("y2", "164");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
                //minus icon 3
               var circle3 = document.createElementNS(svgNS, "circle");
               circle3.setAttribute("cx", "243");
               circle3.setAttribute("cy", "214");
               circle3.setAttribute("r", "10");
               circle3.setAttribute("stroke", "#EFFBF2");
               circle3.setAttribute("stroke-width", "1");
               circle3.setAttribute("fill", "#D8D8D8");
               circle3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle3.onmouseover = function(){this.style.fill = "black";};
               circle3.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line3 = document.createElementNS(svgNS, "line");
               line3.setAttribute("x1", "237");
               line3.setAttribute("y1", "214");
               line3.setAttribute("x2", "249");
               line3.setAttribute("y2", "214");
               line3.setAttribute("stroke-width", "4");
               line3.setAttribute("stroke", "white");
               line3.onmouseover = function(){circle3.style.fill = "black";};
               line3.onmouseout = function(){circle3.style.fill = "#D8D8D8";};
               line3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle3);
               svgEle.appendChild(line3);
                //minus icon 4
               var circle4 = document.createElementNS(svgNS, "circle");
               circle4.setAttribute("cx", "200");
               circle4.setAttribute("cy", "245");
               circle4.setAttribute("r", "10");
               circle4.setAttribute("stroke", "#EFFBF2");
               circle4.setAttribute("stroke-width", "1");
               circle4.setAttribute("fill", "#D8D8D8");
               circle4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle4.onmouseover = function(){this.style.fill = "black";};
               circle4.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line4 = document.createElementNS(svgNS, "line");
               line4.setAttribute("x1", "194");
               line4.setAttribute("y1", "245");
               line4.setAttribute("x2", "206");
               line4.setAttribute("y2", "245");
               line4.setAttribute("stroke-width", "4");
               line4.setAttribute("stroke", "white");
               line4.onmouseover = function(){circle4.style.fill = "black";};
               line4.onmouseout = function(){circle4.style.fill = "#D8D8D8";};
               line4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle4);
               svgEle.appendChild(line4); 
                //minus icon 5
               var circle5 = document.createElementNS(svgNS, "circle");
               circle5.setAttribute("cx", "157");
               circle5.setAttribute("cy", "214");
               circle5.setAttribute("r", "10");
               circle5.setAttribute("stroke", "#EFFBF2");
               circle5.setAttribute("stroke-width", "1");
               circle5.setAttribute("fill", "#D8D8D8");
               circle5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle5.onmouseover = function(){this.style.fill = "black";};
               circle5.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line5 = document.createElementNS(svgNS, "line");
               line5.setAttribute("x1", "151");
               line5.setAttribute("y1", "214");
               line5.setAttribute("x2", "163");
               line5.setAttribute("y2", "214");
               line5.setAttribute("stroke-width", "4");
               line5.setAttribute("stroke", "white");
               line5.onmouseover = function(){circle5.style.fill = "black";};
               line5.onmouseout = function(){circle5.style.fill = "#D8D8D8";};
               line5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle5);
               svgEle.appendChild(line5); 
          }
          break;
	}
	case 6:{
		//circle + six triangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first triangle
          	var tri1 = document.createElementNS(svgNS, "polygon");
          	tri1.setAttribute("points", formatBuilder({x:200, y:0}, {x:373, y:100}, {x:200, y:200}));
          	tri1.setAttribute("stroke-width", "1");
          	tri1.setAttribute("stroke", "black");
          	tri1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri1.style.fill = "#58ACFA";
          	tri1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second triangle
          	var tri2 = document.createElementNS(svgNS, "polygon");
          	tri2.setAttribute("points", formatBuilder({x:373, y:100}, {x:373, y:300}, {x:200, y:200}));
          	tri2.setAttribute("stroke-width", "1");
          	tri2.setAttribute("stroke", "black");
          	tri2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri2.style.fill = "#58ACFA";
          	tri2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//third triangle
          	var tri3 = document.createElementNS(svgNS, "polygon");
          	tri3.setAttribute("points", formatBuilder({x:373, y:300}, {x:200, y:400}, {x:200, y:200}));
          	tri3.setAttribute("stroke-width", "1");
          	tri3.setAttribute("stroke", "black");
          	tri3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri3.style.fill = "#58ACFA";
          	tri3.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri3.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//forth triangle
          	var tri4 = document.createElementNS(svgNS, "polygon");
          	tri4.setAttribute("points", formatBuilder({x:200, y:400}, {x:27, y:300}, {x:200, y:200}));
          	tri4.setAttribute("stroke-width", "1");
          	tri4.setAttribute("stroke", "black");
          	tri4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri4.style.fill = "#58ACFA";
          	tri4.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri4.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//fifth triangle
          	var tri5 = document.createElementNS(svgNS, "polygon");
          	tri5.setAttribute("points", formatBuilder({x:27, y:300}, {x:27, y:100}, {x:200, y:200}));
          	tri5.setAttribute("stroke-width", "1");
          	tri5.setAttribute("stroke", "black");
          	tri5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri5.style.fill = "#58ACFA";
          	tri5.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri5.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//sixth triangle
          	var tri6 = document.createElementNS(svgNS, "polygon");
          	tri6.setAttribute("points", formatBuilder({x:27, y:100}, {x:200, y:0}, {x:200, y:200}));
          	tri6.setAttribute("stroke-width", "1");
          	tri6.setAttribute("stroke", "black");
          	tri6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri6.style.fill = "#58ACFA";
          	tri6.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri6.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(tri1);
          	svgEle.appendChild(tri2);
          	svgEle.appendChild(tri3);
          	svgEle.appendChild(tri4);
          	svgEle.appendChild(tri5);
          	svgEle.appendChild(tri6);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "139");
          	text1.setAttribute("y", "85");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "259");
          	text2.setAttribute("y", "85");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text3 = document.createElementNS(svgNS, "text");
          	text3.setAttribute("x", "331");
          	text3.setAttribute("y", "200");
          	text3.setAttribute("fill", "black");
          	text3.textContent = "3";
          	svgEle.appendChild(text3);
          	var text4 = document.createElementNS(svgNS, "text");
          	text4.setAttribute("x", "259");
          	text4.setAttribute("y", "315");
          	text4.setAttribute("fill", "black");
          	text4.textContent = "4";
          	svgEle.appendChild(text4);
          	var text5 = document.createElementNS(svgNS, "text");
          	text5.setAttribute("x", "138");
          	text5.setAttribute("y", "315");
          	text5.setAttribute("fill", "black");
          	text5.textContent = "5";
          	svgEle.appendChild(text5);
          	var text6 = document.createElementNS(svgNS, "text");
          	text6.setAttribute("x", "67");
          	text6.setAttribute("y", "200");
          	text6.setAttribute("fill", "black");
          	text6.textContent = "6";
          	svgEle.appendChild(text6);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
               //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "178");
               circle1.setAttribute("cy", "161");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "172");
               line1.setAttribute("y1", "161");
               line1.setAttribute("x2", "184");
               line1.setAttribute("y2", "161");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "222");
               circle2.setAttribute("cy", "161");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "216");
               line2.setAttribute("y1", "161");
               line2.setAttribute("x2", "228");
               line2.setAttribute("y2", "161");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
                //minus icon 3
               var circle3 = document.createElementNS(svgNS, "circle");
               circle3.setAttribute("cx", "245");
               circle3.setAttribute("cy", "200");
               circle3.setAttribute("r", "10");
               circle3.setAttribute("stroke", "#EFFBF2");
               circle3.setAttribute("stroke-width", "1");
               circle3.setAttribute("fill", "#D8D8D8");
               circle3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle3.onmouseover = function(){this.style.fill = "black";};
               circle3.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line3 = document.createElementNS(svgNS, "line");
               line3.setAttribute("x1", "239");
               line3.setAttribute("y1", "200");
               line3.setAttribute("x2", "251");
               line3.setAttribute("y2", "200");
               line3.setAttribute("stroke-width", "4");
               line3.setAttribute("stroke", "white");
               line3.onmouseover = function(){circle3.style.fill = "black";};
               line3.onmouseout = function(){circle3.style.fill = "#D8D8D8";};
               line3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle3);
               svgEle.appendChild(line3);
                //minus icon 4
               var circle4 = document.createElementNS(svgNS, "circle");
               circle4.setAttribute("cx", "222");
               circle4.setAttribute("cy", "239");
               circle4.setAttribute("r", "10");
               circle4.setAttribute("stroke", "#EFFBF2");
               circle4.setAttribute("stroke-width", "1");
               circle4.setAttribute("fill", "#D8D8D8");
               circle4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle4.onmouseover = function(){this.style.fill = "black";};
               circle4.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line4 = document.createElementNS(svgNS, "line");
               line4.setAttribute("x1", "216");
               line4.setAttribute("y1", "239");
               line4.setAttribute("x2", "228");
               line4.setAttribute("y2", "239");
               line4.setAttribute("stroke-width", "4");
               line4.setAttribute("stroke", "white");
               line4.onmouseover = function(){circle4.style.fill = "black";};
               line4.onmouseout = function(){circle4.style.fill = "#D8D8D8";};
               line4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle4);
               svgEle.appendChild(line4); 
                //minus icon 5
               var circle5 = document.createElementNS(svgNS, "circle");
               circle5.setAttribute("cx", "178");
               circle5.setAttribute("cy", "239");
               circle5.setAttribute("r", "10");
               circle5.setAttribute("stroke", "#EFFBF2");
               circle5.setAttribute("stroke-width", "1");
               circle5.setAttribute("fill", "#D8D8D8");
               circle5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle5.onmouseover = function(){this.style.fill = "black";};
               circle5.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line5 = document.createElementNS(svgNS, "line");
               line5.setAttribute("x1", "172");
               line5.setAttribute("y1", "239");
               line5.setAttribute("x2", "184");
               line5.setAttribute("y2", "239");
               line5.setAttribute("stroke-width", "4");
               line5.setAttribute("stroke", "white");
               line5.onmouseover = function(){circle5.style.fill = "black";};
               line5.onmouseout = function(){circle5.style.fill = "#D8D8D8";};
               line5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle5);
               svgEle.appendChild(line5); 
                //minus icon 6
               var circle6 = document.createElementNS(svgNS, "circle");
               circle6.setAttribute("cx", "155");
               circle6.setAttribute("cy", "200");
               circle6.setAttribute("r", "10");
               circle6.setAttribute("stroke", "#EFFBF2");
               circle6.setAttribute("stroke-width", "1");
               circle6.setAttribute("fill", "#D8D8D8");
               circle6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle6.onmouseover = function(){this.style.fill = "black";};
               circle6.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line6 = document.createElementNS(svgNS, "line");
               line6.setAttribute("x1", "149");
               line6.setAttribute("y1", "200");
               line6.setAttribute("x2", "161");
               line6.setAttribute("y2", "200");
               line6.setAttribute("stroke-width", "4");
               line6.setAttribute("stroke", "white");
               line6.onmouseover = function(){circle6.style.fill = "black";};
               line6.onmouseout = function(){circle6.style.fill = "#D8D8D8";};
               line6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle6);
               svgEle.appendChild(line6); 
          }
          break;
	}
	case 7:{
		//circle + six triangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first triangle
          	var tri1 = document.createElementNS(svgNS, "polygon");
          	tri1.setAttribute("points", formatBuilder({x:200, y:0}, {x:356, y:75}, {x:200, y:200}));
          	tri1.setAttribute("stroke-width", "1");
          	tri1.setAttribute("stroke", "black");
          	tri1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri1.style.fill = "#58ACFA";
          	tri1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second triangle
          	var tri2 = document.createElementNS(svgNS, "polygon");
          	tri2.setAttribute("points", formatBuilder({x:356, y:75}, {x:395, y:245}, {x:200, y:200}));
          	tri2.setAttribute("stroke-width", "1");
          	tri2.setAttribute("stroke", "black");
          	tri2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri2.style.fill = "#58ACFA";
          	tri2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//third triangle
          	var tri3 = document.createElementNS(svgNS, "polygon");
          	tri3.setAttribute("points", formatBuilder({x:395, y:245}, {x:287, y:380}, {x:200, y:200}));
          	tri3.setAttribute("stroke-width", "1");
          	tri3.setAttribute("stroke", "black");
          	tri3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri3.style.fill = "#58ACFA";
          	tri3.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri3.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//forth triangle
          	var tri4 = document.createElementNS(svgNS, "polygon");
          	tri4.setAttribute("points", formatBuilder({x:287, y:380}, {x:113, y:380}, {x:200, y:200}));
          	tri4.setAttribute("stroke-width", "1");
          	tri4.setAttribute("stroke", "black");
          	tri4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri4.style.fill = "#58ACFA";
          	tri4.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri4.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//fifth triangle
          	var tri5 = document.createElementNS(svgNS, "polygon");
          	tri5.setAttribute("points", formatBuilder({x:113, y:380}, {x:5, y:245}, {x:200, y:200}));
          	tri5.setAttribute("stroke-width", "1");
          	tri5.setAttribute("stroke", "black");
          	tri5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri5.style.fill = "#58ACFA";
          	tri5.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri5.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//sixth triangle
          	var tri6 = document.createElementNS(svgNS, "polygon");
          	tri6.setAttribute("points", formatBuilder({x:5, y:245}, {x:44, y:75}, {x:200, y:200}));
          	tri6.setAttribute("stroke-width", "1");
          	tri6.setAttribute("stroke", "black");
          	tri6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri6.style.fill = "#58ACFA";
          	tri6.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri6.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//seventh triangle
          	var tri7 = document.createElementNS(svgNS, "polygon");
          	tri7.setAttribute("points", formatBuilder({x:44, y:75}, {x:200, y:0}, {x:200, y:200}));
          	tri7.setAttribute("stroke-width", "1");
          	tri7.setAttribute("stroke", "black");
          	tri7.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri7.style.fill = "#58ACFA";
          	tri7.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri7.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(tri1);
          	svgEle.appendChild(tri2);
          	svgEle.appendChild(tri3);
          	svgEle.appendChild(tri4);
          	svgEle.appendChild(tri5);
          	svgEle.appendChild(tri6);
          	svgEle.appendChild(tri7);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "137");
          	text1.setAttribute("y", "63");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "261");
          	text2.setAttribute("y", "63");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text3 = document.createElementNS(svgNS, "text");
          	text3.setAttribute("x", "348");
          	text3.setAttribute("y", "170");
          	text3.setAttribute("fill", "black");
          	text3.textContent = "3";
          	svgEle.appendChild(text3);
          	var text4 = document.createElementNS(svgNS, "text");
          	text4.setAttribute("x", "309");
          	text4.setAttribute("y", "297");
          	text4.setAttribute("fill", "black");
          	text4.textContent = "4";
          	svgEle.appendChild(text4);
          	var text5 = document.createElementNS(svgNS, "text");
          	text5.setAttribute("x", "200");
          	text5.setAttribute("y", "345");
          	text5.setAttribute("fill", "black");
          	text5.textContent = "5";
          	svgEle.appendChild(text5);
          	var text6 = document.createElementNS(svgNS, "text");
          	text6.setAttribute("x", "89");
          	text6.setAttribute("y", "297");
          	text6.setAttribute("fill", "black");
          	text6.textContent = "6";
          	svgEle.appendChild(text6);
          	var text7 = document.createElementNS(svgNS, "text");
          	text7.setAttribute("x", "50");
          	text7.setAttribute("y", "170");
          	text7.setAttribute("fill", "black");
          	text7.textContent = "7";
          	svgEle.appendChild(text7);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
               //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "180");
               circle1.setAttribute("cy", "160");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "174");
               line1.setAttribute("y1", "160");
               line1.setAttribute("x2", "186");
               line1.setAttribute("y2", "160");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "220");
               circle2.setAttribute("cy", "160");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "214");
               line2.setAttribute("y1", "160");
               line2.setAttribute("x2", "226");
               line2.setAttribute("y2", "160");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
                //minus icon 3
               var circle3 = document.createElementNS(svgNS, "circle");
               circle3.setAttribute("cx", "244");
               circle3.setAttribute("cy", "190");
               circle3.setAttribute("r", "10");
               circle3.setAttribute("stroke", "#EFFBF2");
               circle3.setAttribute("stroke-width", "1");
               circle3.setAttribute("fill", "#D8D8D8");
               circle3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle3.onmouseover = function(){this.style.fill = "black";};
               circle3.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line3 = document.createElementNS(svgNS, "line");
               line3.setAttribute("x1", "238");
               line3.setAttribute("y1", "190");
               line3.setAttribute("x2", "250");
               line3.setAttribute("y2", "190");
               line3.setAttribute("stroke-width", "4");
               line3.setAttribute("stroke", "white");
               line3.onmouseover = function(){circle3.style.fill = "black";};
               line3.onmouseout = function(){circle3.style.fill = "#D8D8D8";};
               line3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle3);
               svgEle.appendChild(line3);
                //minus icon 4
               var circle4 = document.createElementNS(svgNS, "circle");
               circle4.setAttribute("cx", "235");
               circle4.setAttribute("cy", "228");
               circle4.setAttribute("r", "10");
               circle4.setAttribute("stroke", "#EFFBF2");
               circle4.setAttribute("stroke-width", "1");
               circle4.setAttribute("fill", "#D8D8D8");
               circle4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle4.onmouseover = function(){this.style.fill = "black";};
               circle4.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line4 = document.createElementNS(svgNS, "line");
               line4.setAttribute("x1", "229");
               line4.setAttribute("y1", "228");
               line4.setAttribute("x2", "241");
               line4.setAttribute("y2", "228");
               line4.setAttribute("stroke-width", "4");
               line4.setAttribute("stroke", "white");
               line4.onmouseover = function(){circle4.style.fill = "black";};
               line4.onmouseout = function(){circle4.style.fill = "#D8D8D8";};
               line4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle4);
               svgEle.appendChild(line4); 
                //minus icon 5
               var circle5 = document.createElementNS(svgNS, "circle");
               circle5.setAttribute("cx", "200");
               circle5.setAttribute("cy", "245");
               circle5.setAttribute("r", "10");
               circle5.setAttribute("stroke", "#EFFBF2");
               circle5.setAttribute("stroke-width", "1");
               circle5.setAttribute("fill", "#D8D8D8");
               circle5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle5.onmouseover = function(){this.style.fill = "black";};
               circle5.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line5 = document.createElementNS(svgNS, "line");
               line5.setAttribute("x1", "194");
               line5.setAttribute("y1", "245");
               line5.setAttribute("x2", "206");
               line5.setAttribute("y2", "245");
               line5.setAttribute("stroke-width", "4");
               line5.setAttribute("stroke", "white");
               line5.onmouseover = function(){circle5.style.fill = "black";};
               line5.onmouseout = function(){circle5.style.fill = "#D8D8D8";};
               line5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle5);
               svgEle.appendChild(line5); 
                //minus icon 6
               var circle6 = document.createElementNS(svgNS, "circle");
               circle6.setAttribute("cx", "165");
               circle6.setAttribute("cy", "228");
               circle6.setAttribute("r", "10");
               circle6.setAttribute("stroke", "#EFFBF2");
               circle6.setAttribute("stroke-width", "1");
               circle6.setAttribute("fill", "#D8D8D8");
               circle6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle6.onmouseover = function(){this.style.fill = "black";};
               circle6.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line6 = document.createElementNS(svgNS, "line");
               line6.setAttribute("x1", "159");
               line6.setAttribute("y1", "228");
               line6.setAttribute("x2", "171");
               line6.setAttribute("y2", "228");
               line6.setAttribute("stroke-width", "4");
               line6.setAttribute("stroke", "white");
               line6.onmouseover = function(){circle6.style.fill = "black";};
               line6.onmouseout = function(){circle6.style.fill = "#D8D8D8";};
               line6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle6);
               svgEle.appendChild(line6); 
               //minus icon 7
               var circle7 = document.createElementNS(svgNS, "circle");
               circle7.setAttribute("cx", "156");
               circle7.setAttribute("cy", "190");
               circle7.setAttribute("r", "10");
               circle7.setAttribute("stroke", "#EFFBF2");
               circle7.setAttribute("stroke-width", "1");
               circle7.setAttribute("fill", "#D8D8D8");
               circle7.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle7.onmouseover = function(){this.style.fill = "black";};
               circle7.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line7 = document.createElementNS(svgNS, "line");
               line7.setAttribute("x1", "150");
               line7.setAttribute("y1", "190");
               line7.setAttribute("x2", "162");
               line7.setAttribute("y2", "190");
               line7.setAttribute("stroke-width", "4");
               line7.setAttribute("stroke", "white");
               line7.onmouseover = function(){circle7.style.fill = "black";};
               line7.onmouseout = function(){circle7.style.fill = "#D8D8D8";};
               line7.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle7);
               svgEle.appendChild(line7); 
          }
          break;
	}
	case 8:{
		//circle + six triangles
		function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("Lab");
          	//circle
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "60");
          	circle.setAttribute("stroke-width", "3");
          	circle.setAttribute("stroke", "black");
          	circle.style.fill = "#A9F5D0";
          	//first triangle
          	var tri1 = document.createElementNS(svgNS, "polygon");
          	tri1.setAttribute("points", formatBuilder({x:200, y:0}, {x:341, y:59}, {x:200, y:200}));
          	tri1.setAttribute("stroke-width", "1");
          	tri1.setAttribute("stroke", "black");
          	tri1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri1.style.fill = "#58ACFA";
          	tri1.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri1.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//second triangle
          	var tri2 = document.createElementNS(svgNS, "polygon");
          	tri2.setAttribute("points", formatBuilder({x:341, y:59}, {x:400, y:200}, {x:200, y:200}));
          	tri2.setAttribute("stroke-width", "1");
          	tri2.setAttribute("stroke", "black");
          	tri2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri2.style.fill = "#58ACFA";
          	tri2.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri2.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//third triangle
          	var tri3 = document.createElementNS(svgNS, "polygon");
          	tri3.setAttribute("points", formatBuilder({x:400, y:200}, {x:341, y:341}, {x:200, y:200}));
          	tri3.setAttribute("stroke-width", "1");
          	tri3.setAttribute("stroke", "black");
          	tri3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri3.style.fill = "#58ACFA";
          	tri3.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri3.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//forth triangle
          	var tri4 = document.createElementNS(svgNS, "polygon");
          	tri4.setAttribute("points", formatBuilder({x:341, y:341}, {x:200, y:400}, {x:200, y:200}));
          	tri4.setAttribute("stroke-width", "1");
          	tri4.setAttribute("stroke", "black");
          	tri4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri4.style.fill = "#58ACFA";
          	tri4.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri4.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//fifth triangle
          	var tri5 = document.createElementNS(svgNS, "polygon");
          	tri5.setAttribute("points", formatBuilder({x:200, y:400}, {x:59, y:341}, {x:200, y:200}));
          	tri5.setAttribute("stroke-width", "1");
          	tri5.setAttribute("stroke", "black");
          	tri5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri5.style.fill = "#58ACFA";
          	tri5.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri5.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//sixth triangle
          	var tri6 = document.createElementNS(svgNS, "polygon");
          	tri6.setAttribute("points", formatBuilder({x:59, y:341}, {x:0, y:200}, {x:200, y:200}));
          	tri6.setAttribute("stroke-width", "1");
          	tri6.setAttribute("stroke", "black");
          	tri6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri6.style.fill = "#58ACFA";
          	tri6.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri6.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//seventh triangle
          	var tri7 = document.createElementNS(svgNS, "polygon");
          	tri7.setAttribute("points", formatBuilder({x:0, y:200}, {x:59, y:59}, {x:200, y:200}));
          	tri7.setAttribute("stroke-width", "1");
          	tri7.setAttribute("stroke", "black");
          	tri7.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri7.style.fill = "#58ACFA";
          	tri7.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri7.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//eighth triangle
          	var tri8 = document.createElementNS(svgNS, "polygon");
          	tri8.setAttribute("points", formatBuilder({x:59, y:59}, {x:200, y:0}, {x:200, y:200}));
          	tri8.setAttribute("stroke-width", "1");
          	tri8.setAttribute("stroke", "black");
          	tri8.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
          	tri8.style.fill = "#58ACFA";
          	tri8.onmouseover = function(){this.style.fill = "#A9E2F3"};
          	tri8.onmouseout = function(){this.style.fill = "#58ACFA";};
          	//append
          	svgEle.appendChild(tri1);
          	svgEle.appendChild(tri2);
          	svgEle.appendChild(tri3);
          	svgEle.appendChild(tri4);
          	svgEle.appendChild(tri5);
          	svgEle.appendChild(tri6);
          	svgEle.appendChild(tri7);
          	svgEle.appendChild(tri8);
          	svgEle.appendChild(circle);
          	//text
          	var text1 = document.createElementNS(svgNS, "text");
          	text1.setAttribute("x", "155");
          	text1.setAttribute("y", "80");
          	text1.setAttribute("fill", "black");
          	text1.textContent = "1";
          	svgEle.appendChild(text1);
          	var text2 = document.createElementNS(svgNS, "text");
          	text2.setAttribute("x", "243");
          	text2.setAttribute("y", "80");
          	text2.setAttribute("fill", "black");
          	text2.textContent = "2";
          	svgEle.appendChild(text2);
          	var text3 = document.createElementNS(svgNS, "text");
          	text3.setAttribute("x", "318");
          	text3.setAttribute("y", "155");
          	text3.setAttribute("fill", "black");
          	text3.textContent = "3";
          	svgEle.appendChild(text3);
          	var text4 = document.createElementNS(svgNS, "text");
          	text4.setAttribute("x", "318");
          	text4.setAttribute("y", "245");
          	text4.setAttribute("fill", "black");
          	text4.textContent = "4";
          	svgEle.appendChild(text4);
          	var text5 = document.createElementNS(svgNS, "text");
          	text5.setAttribute("x", "243");
          	text5.setAttribute("y", "320");
          	text5.setAttribute("fill", "black");
          	text5.textContent = "5";
          	svgEle.appendChild(text5);
          	var text6 = document.createElementNS(svgNS, "text");
          	text6.setAttribute("x", "155");
          	text6.setAttribute("y", "320");
          	text6.setAttribute("fill", "black");
          	text6.textContent = "6";
          	svgEle.appendChild(text6);
          	var text7 = document.createElementNS(svgNS, "text");
          	text7.setAttribute("x", "80");
          	text7.setAttribute("y", "245");
          	text7.setAttribute("fill", "black");
          	text7.textContent = "7";
          	svgEle.appendChild(text7);
          	var text8 = document.createElementNS(svgNS, "text");
          	text8.setAttribute("x", "80");
          	text8.setAttribute("y", "155");
          	text8.setAttribute("fill", "black");
          	text8.textContent = "8";
          	svgEle.appendChild(text8);
          	var text = document.createElementNS(svgNS, "text");
          	text.setAttribute("x", "178");
          	text.setAttribute("y", "205");
          	text.setAttribute("fill", "black");
          	text.textContent = "LabXX";
          	svgEle.appendChild(text);
                //minus icon 1
               var circle1 = document.createElementNS(svgNS, "circle");
               circle1.setAttribute("cx", "183");
               circle1.setAttribute("cy", "158");
               circle1.setAttribute("r", "10");
               circle1.setAttribute("stroke", "#EFFBF2");
               circle1.setAttribute("stroke-width", "1");
               circle1.setAttribute("fill", "#D8D8D8");
               circle1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle1.onmouseover = function(){this.style.fill = "black";};
               circle1.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line1 = document.createElementNS(svgNS, "line");
               line1.setAttribute("x1", "177");
               line1.setAttribute("y1", "158");
               line1.setAttribute("x2", "189");
               line1.setAttribute("y2", "158");
               line1.setAttribute("stroke-width", "4");
               line1.setAttribute("stroke", "white");
               line1.onmouseover = function(){circle1.style.fill = "black";};
               line1.onmouseout = function(){circle1.style.fill = "#D8D8D8";};
               line1.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle1);
               svgEle.appendChild(line1);
                //minus icon 2
               var circle2 = document.createElementNS(svgNS, "circle");
               circle2.setAttribute("cx", "217");
               circle2.setAttribute("cy", "158");
               circle2.setAttribute("r", "10");
               circle2.setAttribute("stroke", "#EFFBF2");
               circle2.setAttribute("stroke-width", "1");
               circle2.setAttribute("fill", "#D8D8D8");
               circle2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle2.onmouseover = function(){this.style.fill = "black";};
               circle2.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line2 = document.createElementNS(svgNS, "line");
               line2.setAttribute("x1", "211");
               line2.setAttribute("y1", "158");
               line2.setAttribute("x2", "223");
               line2.setAttribute("y2", "158");
               line2.setAttribute("stroke-width", "4");
               line2.setAttribute("stroke", "white");
               line2.onmouseover = function(){circle2.style.fill = "black";};
               line2.onmouseout = function(){circle2.style.fill = "#D8D8D8";};
               line2.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle2);
               svgEle.appendChild(line2);
                //minus icon 3
               var circle3 = document.createElementNS(svgNS, "circle");
               circle3.setAttribute("cx", "242");
               circle3.setAttribute("cy", "183");
               circle3.setAttribute("r", "10");
               circle3.setAttribute("stroke", "#EFFBF2");
               circle3.setAttribute("stroke-width", "1");
               circle3.setAttribute("fill", "#D8D8D8");
               circle3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle3.onmouseover = function(){this.style.fill = "black";};
               circle3.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line3 = document.createElementNS(svgNS, "line");
               line3.setAttribute("x1", "236");
               line3.setAttribute("y1", "183");
               line3.setAttribute("x2", "248");
               line3.setAttribute("y2", "183");
               line3.setAttribute("stroke-width", "4");
               line3.setAttribute("stroke", "white");
               line3.onmouseover = function(){circle3.style.fill = "black";};
               line3.onmouseout = function(){circle3.style.fill = "#D8D8D8";};
               line3.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle3);
               svgEle.appendChild(line3);
                //minus icon 4
               var circle4 = document.createElementNS(svgNS, "circle");
               circle4.setAttribute("cx", "242");
               circle4.setAttribute("cy", "217");
               circle4.setAttribute("r", "10");
               circle4.setAttribute("stroke", "#EFFBF2");
               circle4.setAttribute("stroke-width", "1");
               circle4.setAttribute("fill", "#D8D8D8");
               circle4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle4.onmouseover = function(){this.style.fill = "black";};
               circle4.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line4 = document.createElementNS(svgNS, "line");
               line4.setAttribute("x1", "248");
               line4.setAttribute("y1", "217");
               line4.setAttribute("x2", "236");
               line4.setAttribute("y2", "217");
               line4.setAttribute("stroke-width", "4");
               line4.setAttribute("stroke", "white");
               line4.onmouseover = function(){circle4.style.fill = "black";};
               line4.onmouseout = function(){circle4.style.fill = "#D8D8D8";};
               line4.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle4);
               svgEle.appendChild(line4); 
                //minus icon 5
               var circle5 = document.createElementNS(svgNS, "circle");
               circle5.setAttribute("cx", "217");
               circle5.setAttribute("cy", "242");
               circle5.setAttribute("r", "10");
               circle5.setAttribute("stroke", "#EFFBF2");
               circle5.setAttribute("stroke-width", "1");
               circle5.setAttribute("fill", "#D8D8D8");
               circle5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle5.onmouseover = function(){this.style.fill = "black";};
               circle5.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line5 = document.createElementNS(svgNS, "line");
               line5.setAttribute("x1", "211");
               line5.setAttribute("y1", "242");
               line5.setAttribute("x2", "223");
               line5.setAttribute("y2", "242");
               line5.setAttribute("stroke-width", "4");
               line5.setAttribute("stroke", "white");
               line5.onmouseover = function(){circle5.style.fill = "black";};
               line5.onmouseout = function(){circle5.style.fill = "#D8D8D8";};
               line5.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle5);
               svgEle.appendChild(line5); 
                //minus icon 6
               var circle6 = document.createElementNS(svgNS, "circle");
               circle6.setAttribute("cx", "183");
               circle6.setAttribute("cy", "242");
               circle6.setAttribute("r", "10");
               circle6.setAttribute("stroke", "#EFFBF2");
               circle6.setAttribute("stroke-width", "1");
               circle6.setAttribute("fill", "#D8D8D8");
               circle6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle6.onmouseover = function(){this.style.fill = "black";};
               circle6.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line6 = document.createElementNS(svgNS, "line");
               line6.setAttribute("x1", "177");
               line6.setAttribute("y1", "242");
               line6.setAttribute("x2", "189");
               line6.setAttribute("y2", "242");
               line6.setAttribute("stroke-width", "4");
               line6.setAttribute("stroke", "white");
               line6.onmouseover = function(){circle6.style.fill = "black";};
               line6.onmouseout = function(){circle6.style.fill = "#D8D8D8";};
               line6.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle6);
               svgEle.appendChild(line6); 
               //minus icon 7
               var circle7 = document.createElementNS(svgNS, "circle");
               circle7.setAttribute("cx", "158");
               circle7.setAttribute("cy", "217");
               circle7.setAttribute("r", "10");
               circle7.setAttribute("stroke", "#EFFBF2");
               circle7.setAttribute("stroke-width", "1");
               circle7.setAttribute("fill", "#D8D8D8");
               circle7.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle7.onmouseover = function(){this.style.fill = "black";};
               circle7.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line7 = document.createElementNS(svgNS, "line");
               line7.setAttribute("x1", "152");
               line7.setAttribute("y1", "217");
               line7.setAttribute("x2", "164");
               line7.setAttribute("y2", "217");
               line7.setAttribute("stroke-width", "4");
               line7.setAttribute("stroke", "white");
               line7.onmouseover = function(){circle7.style.fill = "black";};
               line7.onmouseout = function(){circle7.style.fill = "#D8D8D8";};
               line7.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle7);
               svgEle.appendChild(line7); 
               //minus icon 8
               var circle8 = document.createElementNS(svgNS, "circle");
               circle8.setAttribute("cx", "158");
               circle8.setAttribute("cy", "183");
               circle8.setAttribute("r", "10");
               circle8.setAttribute("stroke", "#EFFBF2");
               circle8.setAttribute("stroke-width", "1");
               circle8.setAttribute("fill", "#D8D8D8");
               circle8.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               circle8.onmouseover = function(){this.style.fill = "black";};
               circle8.onmouseout = function(){this.style.fill = "#D8D8D8";};
               var line8 = document.createElementNS(svgNS, "line");
               line8.setAttribute("x1", "152");
               line8.setAttribute("y1", "183");
               line8.setAttribute("x2", "164");
               line8.setAttribute("y2", "183");
               line8.setAttribute("stroke-width", "4");
               line8.setAttribute("stroke", "white");
               line8.onmouseover = function(){circle8.style.fill = "black";};
               line8.onmouseout = function(){circle8.style.fill = "#D8D8D8";};
               line8.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
               svgEle.appendChild(circle8);
               svgEle.appendChild(line8); 
          }
          break;
	}
	case 9:{
		
        function createPolygon() {
          	var svgNS = "http://www.w3.org/2000/svg";
          	var svgEle = document.getElementById("demo");
          	var polygonEle = document.createElementNS(svgNS, "polygon");
          	polygonEle.setAttribute("points", formatBuilder({x:200, y:10}, {x:250, y:190}, {x:160, y:210}));
	    	polygonEle.onclick = function(){window.location.assign("http://www.ntu.edu.tw/");};
	    	polygonEle.onmouseover = function(){this.style.fill = "silver";};
	    	polygonEle.onmouseout = function(){this.style.fill = "gray";};
          	svgEle.appendChild(polygonEle);
          	var poly = document.createElementNS(svgNS, "polygon");
          	poly.setAttribute("points", formatBuilder({x:200, y:200}, {x:250, y:200}, {x:200, y:250}));
          	svgEle.appendChild(poly);
          	var circle = document.createElementNS(svgNS, "circle");
          	circle.setAttribute("cx", "200");
          	circle.setAttribute("cy", "200");
          	circle.setAttribute("r", "50");
          	svgEle.appendChild(circle);
        }
        	
	}
}
